import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

export type ActiveAgentStatus = "onboarding" | "active" | "on_leave" | "terminated";

// Types for the unified agents table (active employees view)
export interface ActiveAgent {
  id: string;
  hr_agent_id: string | null;
  user_id: string | null;
  employee_id: string | null;
  full_name: string;
  email: string;
  phone: string | null;
  photo_url: string | null;
  division: string;
  hire_date: string;
  start_date: string | null;
  contract_id: string | null;
  commission_split: string | null;
  status: ActiveAgentStatus;
  onboarding_completed_at: string | null;
  ytd_production: number;
  deals_closed: number;
  last_deal_date: string | null;
  created_at: string;
  updated_at: string;
  created_by: string | null;
}

export interface ActiveAgentInsert {
  hr_agent_id?: string | null;
  user_id?: string | null;
  employee_id?: string | null;
  full_name: string;
  email: string;
  phone?: string | null;
  division: string;
  hire_date: string;
  start_date?: string | null;
  contract_id?: string | null;
  commission_split?: string | null;
  status?: ActiveAgentStatus;
}

export interface ActiveAgentFilters {
  status?: ActiveAgentStatus;
  division?: string;
  search?: string;
}

// Helper function to map agents table row to ActiveAgent interface
function mapToActiveAgent(row: any): ActiveAgent {
  return {
    id: row.id,
    hr_agent_id: row.hr_agent_id,
    user_id: row.user_id,
    employee_id: row.employee_id,
    full_name: row.full_name,
    email: row.email,
    phone: row.phone,
    photo_url: row.photo_url,
    division: row.division || 'residential',
    hire_date: row.hire_date || row.created_at,
    start_date: row.start_date,
    contract_id: row.contract_id,
    commission_split: row.commission_split,
    // Map employment_status to status
    status: row.employment_status as ActiveAgentStatus,
    onboarding_completed_at: row.onboarding_completed_at,
    ytd_production: row.ytd_commission || 0,
    deals_closed: row.ytd_deals || 0,
    last_deal_date: row.last_deal_date,
    created_at: row.created_at,
    updated_at: row.updated_at,
    created_by: row.created_by,
  };
}

export const useActiveAgents = (filters?: ActiveAgentFilters) => {
  return useQuery({
    queryKey: ["active-agents", filters],
    queryFn: async () => {
      let query = supabase
        .from("agents")
        .select("*")
        // Only show active employees (not candidates/recruited)
        .in("employment_status", ["onboarding", "active", "on_leave", "terminated"])
        .order("created_at", { ascending: false });

      if (filters?.status) {
        query = query.eq("employment_status", filters.status);
      }
      if (filters?.division) {
        query = query.eq("division", filters.division);
      }
      if (filters?.search) {
        query = query.or(`full_name.ilike.%${filters.search}%,email.ilike.%${filters.search}%`);
      }

      const { data, error } = await query;
      if (error) throw error;
      return (data || []).map(mapToActiveAgent);
    },
  });
};

export const useActiveAgent = (id: string | undefined) => {
  return useQuery({
    queryKey: ["active-agent", id],
    queryFn: async () => {
      if (!id) return null;
      const { data, error } = await supabase
        .from("agents")
        .select("*")
        .eq("id", id)
        .single();
      if (error) throw error;
      return mapToActiveAgent(data);
    },
    enabled: !!id,
  });
};

export const useCreateActiveAgent = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (agent: ActiveAgentInsert) => {
      const { data: { user } } = await supabase.auth.getUser();
      
      // Insert into unified agents table with active/onboarding status
      // Employee ID will be auto-generated by trigger
      const { data, error } = await supabase
        .from("agents")
        .insert({
          full_name: agent.full_name,
          email: agent.email,
          phone: agent.phone,
          division: agent.division,
          hire_date: agent.hire_date,
          start_date: agent.start_date,
          contract_id: agent.contract_id,
          commission_split: agent.commission_split,
          hr_agent_id: agent.hr_agent_id,
          user_id: agent.user_id,
          employment_status: agent.status || 'onboarding',
          created_by: user?.id,
        })
        .select()
        .single();

      if (error) throw error;

      // Create onboarding record
      await supabase.from("agent_onboarding").insert({
        active_agent_id: data.id,
        contract_signed: !!agent.contract_id,
        contract_signed_at: agent.contract_id ? new Date().toISOString() : null,
      });

      return mapToActiveAgent(data);
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["active-agents"] });
      queryClient.invalidateQueries({ queryKey: ["hr-agents"] });
      toast.success("Active agent created successfully");
    },
    onError: (error) => {
      toast.error(`Failed to create active agent: ${error.message}`);
    },
  });
};

export const useUpdateActiveAgent = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async ({ id, ...updates }: Partial<ActiveAgent> & { id: string }) => {
      // Map status back to employment_status
      const dbUpdates: Record<string, any> = { ...updates };
      if (updates.status) {
        dbUpdates.employment_status = updates.status;
        delete dbUpdates.status;
      }
      // Map ytd_production back to ytd_commission
      if (updates.ytd_production !== undefined) {
        dbUpdates.ytd_commission = updates.ytd_production;
        delete dbUpdates.ytd_production;
      }
      // Map deals_closed back to ytd_deals
      if (updates.deals_closed !== undefined) {
        dbUpdates.ytd_deals = updates.deals_closed;
        delete dbUpdates.deals_closed;
      }

      const { data, error } = await supabase
        .from("agents")
        .update(dbUpdates)
        .eq("id", id)
        .select()
        .single();
      if (error) throw error;
      return mapToActiveAgent(data);
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ["active-agents"] });
      queryClient.invalidateQueries({ queryKey: ["active-agent", data.id] });
      toast.success("Agent updated successfully");
    },
    onError: (error) => {
      toast.error(`Failed to update agent: ${error.message}`);
    },
  });
};

export const useActiveAgentStats = () => {
  return useQuery({
    queryKey: ["active-agent-stats"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("agents")
        .select("employment_status, division")
        .in("employment_status", ["onboarding", "active", "on_leave", "terminated"]);
      if (error) throw error;

      const agents = data as { employment_status: string; division: string | null }[];
      return {
        total: agents.length,
        onboarding: agents.filter((a) => a.employment_status === "onboarding").length,
        active: agents.filter((a) => a.employment_status === "active").length,
        onLeave: agents.filter((a) => a.employment_status === "on_leave").length,
        terminated: agents.filter((a) => a.employment_status === "terminated").length,
        byDivision: {
          residential: agents.filter((a) => a.division === "residential").length,
          commercial: agents.filter((a) => a.division === "commercial-leasing").length,
          investment_sales: agents.filter((a) => a.division === "investment-sales").length,
        },
      };
    },
  });
};

// Status utilities
export const statusConfig: Record<ActiveAgentStatus, { label: string; color: string }> = {
  onboarding: { label: "Onboarding", color: "bg-amber-500/10 text-amber-500 border-amber-500/20" },
  active: { label: "Active", color: "bg-emerald-500/10 text-emerald-500 border-emerald-500/20" },
  on_leave: { label: "On Leave", color: "bg-blue-500/10 text-blue-500 border-blue-500/20" },
  terminated: { label: "Terminated", color: "bg-red-500/10 text-red-500 border-red-500/20" },
};
